custom: 
  service: ${file(env.yml):service}
  awsProfile: ${file(env.yml):awsProfile}
  awsTagName: ${file(env.yml):awsTagName}
  slackUrl: ${file(env.yml):${opt:stage, 'dev'}.slackUrl}

service: ${self:custom.service}

frameworkVersion: ">=1.32.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  memorySize: 128
  profile: ${self:custom.awsProfile} # aws named profile
  stage: ${opt:stage, 'dev'} # `sls deploy --stage production` if --stage is provided, else use dev
  stackTags: # Optional CF stack tags
    Name: ${self:custom.awsTagName}
    Stage: ${opt:stage, 'dev'}
  environment:
    slackUrl: ${self:custom.slackUrl}

functions:
  pinterest:
    handler: pinterest.call
    events:
      - http:
          path: '/test'
          method: get
          cors: true


plugins:
  - serverless-offline